syscalls: compare filesystem types as u64s
libpathrs does not compile on s390x with musl:

    error[E0308]: mismatched types
       --> src/procfs.rs:982:19
        |
    982 |     if fs_type != rustix_fs::PROC_SUPER_MAGIC {
        |        -------    ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`

The core issue is that rustix::fs::StatFs::f_type is not always the same
type as rustix::fs::FsWord (used for the filesystem type constants).
This really should not happen (and is arguably an upstream bug in either
libc or rustix) but we need to work around it by just casting everything
to u64.

The main architecture where this happens is actually a tier 3
architecture which is why we never spotted it (and upstream likely also
missed it for the same reason).

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
Signed-off-by: Aleksa Sarai <aleksa@amutable.com>